Remove callout to associate with batching release on Dev server
inngest/website pull request #677
Opened 2024-02-16 19:22 UTC by darwin67

2024-02-16 19:25 UTC, anafilipadealmeida approved these changes

2024-02-20 11:28 UTC, sylwiavargas commented on pages/docs/guides/batching.mdx
> +Batching breaks a lot of other primitives, therefore there are features that simply doesn't work when combined
```suggestion
Batching breaks a lot of other primitives, therefore there are features that won't work when combined
```

2024-02-20 11:29 UTC, sylwiavargas commented on pages/docs/guides/batching.mdx
> +with batching. This is true for any type of configuration that are operated on a single event because it's impossible
```suggestion
with batching. This is true for any type of configuration which is operated on a single event because it's impossible
```

2024-02-20 11:30 UTC, sylwiavargas requested changes
Thank you! I added some suggestions for style 💜

2024-02-20 18:11 UTC, sylwiavargas approved these changes
Thank you!

2024-02-22 19:12 UTC, merged